"""add_award_fin_history

Revision ID: 46c125c4bf33
Revises: 889892137919
Create Date: 2016-08-09 10:28:10.348434

"""

# revision identifiers, used by Alembic.
revision = '46c125c4bf33'
down_revision = '889892137919'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_financial_history',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('award_financial_history_id', sa.Integer(), nullable=False),
    sa.Column('fieldname', sa.Text(), nullable=False),
    sa.Column('tas', sa.Text(), nullable=False),
    sa.Column('object_class', sa.Text(), nullable=True),
    sa.Column('program_activity', sa.Text(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('award_financial_history_id')
    )
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('award_financial_history')
    ### end Alembic commands ###

