"""add_history_indices

Revision ID: afc12847c4b4
Revises: 46c125c4bf33
Create Date: 2016-08-09 10:43:17.564220

"""

# revision identifiers, used by Alembic.
revision = 'afc12847c4b4'
down_revision = '46c125c4bf33'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_object_class_history', 'award_financial_history', ['fieldname', 'tas', 'object_class', 'fiscal_year', 'quarter'], unique=True)
    op.create_index('ix_program_activity_history', 'award_financial_history', ['fieldname', 'tas', 'program_activity', 'fiscal_year', 'quarter'], unique=True)
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_program_activity_history', table_name='award_financial_history')
    op.drop_index('ix_object_class_history', table_name='award_financial_history')
    ### end Alembic commands ###

