"""add_submission_fk_to_history

Revision ID: b00f6a2eda10
Revises: afc12847c4b4
Create Date: 2016-08-09 12:37:24.195589

"""

# revision identifiers, used by Alembic.
revision = 'b00f6a2eda10'
down_revision = 'afc12847c4b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('award_financial_history', sa.Column('submission_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_history_submission', 'award_financial_history', 'submission', ['submission_id'], ['submission_id'])
    ### end Alembic commands ###


def downgrade_data_broker():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_history_submission', 'award_financial_history', type_='foreignkey')
    op.drop_column('award_financial_history', 'submission_id')
    ### end Alembic commands ###

